### PR TITLE
properties option

### PR DESCRIPTION
**Pull request by charlierudolph**
A simpler interface for having support for both `require` and `require.resolve` instead of having to implement my own `isRequire` function.

### CODE REVIEW

**Comment by charlierudolph** [comment]
@substack any thoughts?

**Comment by charlierudolph** [comment]
@substack bump. I'm fine if you don't want to support this, just looking for some feedback

**Comment by zertosh** [comment]
Hey @charlierudolph, a few things:

* Couldn't you do this by passing in a custom `opts.isRequire`? Especially since the return object's `strings` doesn't contain any info about where the string came from.
* Since the most common use case is to not pass `opts.properties`, why not optimize for it by changing `else if (callee.type === 'MemberExpression' &&` to `else if (properties && callee.type === 'MemberExpression' &&`? (That also means changing `var properties = opts.properties`).
* Your test would also pass if you did `require[resolve]('b');`
* For substack PRs, he likes the extra spaces.

**Comment by charlierudolph** [comment]
> Couldn't you do this by passing in a custom opts.isRequire? Especially since the return object's strings doesn't contain any info about where the string came from.
Yeah that's how I currently support this. Just wanted to move some of that logic in here as I felt require.resolve is a pretty normal thing to do

> Since the most common use case is to not pass opts.properties, why not optimize for it by changing else if (callee.type === 'MemberExpression' && to else if (properties && callee.type === 'MemberExpression' &&? (That also means changing var properties = opts.properties).
ok

> Your test would also pass if you did require[resolve]('b');
I'm fine with that, are you suggesting adding a test case for that?

> For substack PRs, he likes the extra spaces.
So he wants the trailing whitespace? My editor removes that automatically but I can try to put it back

**Comment by zertosh** [comment]
> Yeah that's how I currently support this. Just wanted to move some of that logic in here as I felt require.resolve is a pretty normal thing to do

That's the point of providing a configurable test function, to keep thing custom checks out of the core project :smile: So if it's already working for you, then it makes sense to keep it out.

**Pull request closed without merging**
